# -*- coding: utf-8 -*-
"""nlp_transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZ8P31o9C7F9bMBARCo-3CTKfYRuSJoQ

In the context of transformers and natural language processing (NLP), a "pipeline" refers to a sequence of processing steps that are applied to text data to perform various NLP tasks. Each step in the pipeline represents a specific processing task, and the output of one step becomes the input for the next step. Pipelines are used in transformers to streamline and automate the process of text analysis and NLP tasks.

(Raw text)----->**Tokenizer** -----(Input Id's)----> **MODEL** -----(Logits)---->**Post Processing** (Predictions)
"""

from transformers import pipeline

#zero shot classification
classifier = pipeline("zero-shot-classification")

classifier(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)

#text generation
gen = pipeline('text-generation')
gen("In this course we will teach you")

"""Using any model from the Hub in a pipeline¶
The previous examples used the default model for the task at hand, but you can also choose a particular model from the Hub to use in a pipeline for a specific task — say, text generation. Go to the Model Hub and click on the corresponding tag on the left to display only the supported models for that task. You should get to a page like this one.
"""

generator = pipeline("text-generation", model="distilgpt2")

generator(
  "in this course we will teach you",
  max_length =30,
  num_return_sequences=2
)

#Unmasker (The idea of this task is to fill in the blanks in a given text)

unmasker = pipeline("fill-mask")

unmasker("This course will teach you all about <mask> models.", top_k=5)

#Named entity recognition

ner = pipeline("ner", grouped_entities = True)
ner("My name is Sylvain and I work at Hugging Face in Brooklyn.")

#question answering

question_answer = pipeline("question-answering")

question_answer(
    question="what is the color of the sky?",
    context="The sky is blue. The sky is very high."
)

#summarization

summarizer = pipeline("summarization")

summarizer(
    """
    America has changed dramatically during recent years. Not only has the number of
    graduates in traditional engineering disciplines such as mechanical, civil,
    electrical, chemical, and aeronautical engineering declined, but in most of
    the premier American universities engineering curricula now concentrate on
    and encourage largely the study of engineering science. As a result, there
    are declining offerings in engineering subjects dealing with infrastructure,
    the environment, and related issues, and greater concentration on high
    technology subjects, largely supporting increasingly complex scientific
    developments. While the latter is important, it should not be at the expense
    of more traditional engineering.

    Rapidly developing economies such as China and India, as well as other
    industrial countries in Europe and Asia, continue to encourage and advance
    the teaching of engineering. Both China and India, respectively, graduate
    six and eight times as many traditional engineers as does the United States.
    Other industrial countries at minimum maintain their output, while America
    suffers an increasingly serious decline in the number of engineering graduates
    and a lack of well-educated engineers.
"""
)

#Translation

translator = pipeline("translation", model="Helsinki-NLP/opus-mt-fr-en")

translator("Ce cours est produit par Hugging Face.")